import express from "express";
import dotenv from "dotenv";
import mongoose from "mongoose" ;
import jwt from "jsonwebtoken" ;
import cors from "cors";
import {checkAuth} from "./middleWare.js";
import { Users , Todos} from "./models.js";

const app = express();
app.use(express.json());
const JWT_SECRET = "cake123";


//load environment variables 
dotenv.config();
//use variables from .env
const db_URI = process.env.MONGODB_URI;
const port = process.env.PORT ||  3000;//2330 is your actual choice, and 3000 is just a "safety net."
//CONECT USING URI
mongoose.connect(db_URI)
    .then(() => {console.log("Connected to MongoDB database using env")})
    .catch((err) => { console.log( " Error while connecting to Mongodb : " + err)});

/* The CORS Issue (Crucial)
By default, a browser won't let a website on one "origin" (like a local file or port) talk to a server on another port (3004) for security reasons. You need to tell Express to allow these requests.*/

app.use(cors()); // Put this above your routes

// let USERS = [];
// let userIds = 0 ;

// let TODOS = [];
// let todoIds = 0;

//Sign up , sign in , create todo , get all todos , delete todo , update todo

app.post("/signup" , async (req, res) =>{
    const username = req.body.username ;
    const password = req.body.password ;
    
    //Check if user already exist and then creating account again
    const isPresent = await Users.findOne({
        username : username ,
        password : password
    });

    if( isPresent){
        return res.status(403).json({
            message : "This user already exists ! "
        });
    }

    const newuser = await Users.create({
        // userId : userIds++, //Id gets generated by DB
        username : username,
        password : password
    })
    res.json({
        message : "Successfully signed up ",
        userId : newuser._id
    });

})

app.post("/signin" , async(req, res) =>{
    //1. Get the name and pass 
    //2. check if they matches 
    //3.Generate a token for user if matches 
    //4. Else -> account not created 
    
    const username= req.body.username ;
    const password = req.body.password ;

    //const user  = USERS.find( user => (user.username === userN && user.password === passw ));
    const user = await Users.findOne({
        username : username,
        password : password
    })
    
    if(user){

        const token = jwt.sign({
            username : user.username ,
            userId : user._id
        } , JWT_SECRET);

        return res.status(200).json({
            message : "Succesfully signed in ",
            token : token //SHOULD BE PASSED IN RES
        });
    }

    res.status(400).json({
        message : "Password or Name invalid !!"
    });


})

app.post("/todo" , checkAuth , async(req, res) =>{
    //1. fetch the toke passed and the todoId
    //2. verify the user by token --> done by checkAuth method
    //3. If success in verification ,  add the task to this user's todo list
    //4. else say - user doesnt exist 
    const userId = req.userId ;
    //const todoId = todoIds++;
    const task = req.body.title ;
    const desc = req.body.description;

    await Todos.create({
        userId : userId,
        //todoId : todoId , gets generated by db
        task : task ,
        description : desc
    });

    res.json({
        message : "Task added !"
    });
   

})

app.get("/todos" , checkAuth , async(req, res) =>{
    const userId = req.userId;

    //fetch all todos aof this user
    const userTodos = await Todos.find( {
        userId : userId
    });
    res.json({
        todos : userTodos
    });
})

app.delete("/todo/:todoId" , checkAuth , async(req, res) =>{
    const userId = req.userId ;
    const todoId =req.params.todoId;

    //check if this user has a todo
    //const hasTodo = TODOS.find( t => ( t.todoId === todoId) && (t.userId === userId));
    const deletedTodo = await Todos.deleteOne({
        todoId : todoId,
        userId : userId
    })
    //if deleted
    /* Mongoose’s deleteOne does not return a number. It returns an object that looks like this: { acknowledged: true, deletedCount: 1 }. An object is always "truthy," but it is not "greater than 0" in a mathematical comparisons*/
    if( deletedTodo.deletedCount > 0 > 0 ){
        //TODOS = TODOS.filter( t.todoId !== todoId);
        return res.status(200).json({
            message : "To do deleted"
        });
    }

    res.status(400).json({
        message : "this to do does not exist for the user!!"
    });
    
})


app.listen(port , () => {
    console.log(`Server running on port ${port}` );
});

